import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Link from "next/link";
import { ThemeContext , ThemeProvider} from "./context/ThemeContext";
import { useContext } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav style={{ marginBottom: "20px" }}>
          <Link href="../../dashboard" style={{ marginRight: "10px" }}>Dashboard</Link>
          <Link href="../../dashboard/profile" style={{ marginRight: "10px" }}>Profile</Link>  
          <Link href="../../dashboard/setting" style={{ marginRight: "10px" }}>Settings</Link>
          <Link href="/" style={{ marginRight: "10px" }}>Home</Link>
          <Link href="../Question-3/About" style={{ marginRight: "10px" }}>About</Link>

          {/* <button
        onClick={toggleTheme}
        style={{
          marginLeft: "auto",
          padding: "6px 12px",
          backgroundColor: dark ? "#444" : "#ddd",
          color: dark ? "#fff" : "#000",
          border: "none",
          borderRadius: "5px",
          cursor: "pointer",
        }}
      >
        {dark ? "Light Mode" : "Dark Mode"}
      </button> */}
        </nav>
        <hr />
        <AuthProvider>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
